name: newfitnessapp
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.7.2
  settings_ui: ^2.0.2
  provider: ^6.0.5
  intl: ^0.17.0
  chewie: ^1.7.1
  flutter_launcher_icons: "^0.9.2"
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  google_sign_in: ^6.2.1
  path_provider: ^2.1.2
  path: ^1.8.3
  cloud_firestore: ^4.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/video_thumbnail.jpeg
    - assets/profile_image.jpeg
    - assets/weightlifter.png
    - assets/bgimage.jpeg
    - assets/reformer/reformer_icon.png
    - assets/personalised_routine/personalised_routine_icon.png
    - assets/strength/strength_icon.png
    - assets/stretching/stretching_icon.png
    - assets/cardio/cardio.png
    - assets/reformer/abs_icon.png
    - assets/reformer/back_icon.png
    - assets/reformer/biceps_icon.png
    - assets/reformer/chest_icon.png
    - assets/reformer/thigh_icon.png
    - assets/reformer/shoulder_icon.png
    - assets/reformer/triceps_icon.png
    - assets/reformer/Bent_over_row_thumbnail.png
    - assets/reformer/Bicep_curls_thumbnail.png
    - assets/reformer/Hammer_curls_thumbnail.png
    - assets/reformer/Incline_chest_press_thumbnail.png
    - assets/reformer/Overheard_shoulder_press_thumbnail.png
    - assets/reformer/Push_up_thumbnail.png
    - assets/reformer/Reverse_dumbbell_flies_thumbnail.png
    - assets/reformer/Shoulder_shrug_thumbnail.png
    - assets/reformer/Skull_crusher_thumbnail.png
    - assets/reformer/Triceps_dips_thumbnail.png
    - assets/reformer/TRX_rows_thumbnail.png
    - assets/reformer/Bent_over_row_video.mp4
    - assets/reformer/Bicep_curls_video.mp4
    - assets/reformer/Hammer_curls_video.mp4
    - assets/reformer/Incline_chest_press_video.mp4
    - assets/reformer/Overheard_shoulder_press_video.mp4
    - assets/reformer/Push_up_video.mp4
    - assets/reformer/Reverse_dumbbell_flies_video.mp4
    - assets/reformer/Shoulder_shrug_video.mp4
    - assets/reformer/Skull_crusher_video.mp4
    - assets/reformer/Triceps_dips_video.mp4
    - assets/reformer/TRX_rows_video.mp4
    - assets/cardio/mountain_climbers.mp4
    - assets/cardio/mountain_climbers.png
    - assets/cardio/jumping_jack.png
    - assets/cardio/jumping_jack.mp4
    - assets/strength/Bulgarian_split_squat.png
    - assets/strength/Bulgarian_split_squat.mp4
    - assets/strength/Good_mornings.png
    - assets/strength/Good_mornings.mp4
    - assets/strength/Hip_thrusts.png
    - assets/strength/Hip_thrusts.mp4
    - assets/strength/Leg_push_back.png
    - assets/strength/Leg_push_back.mp4
    - assets/strength/Romanian_deadlift.png
    - assets/strength/Romanian_deadlift.mp4
    - assets/strength/Single_leg_flute_bridge.png
    - assets/strength/Single_leg_flute_bridge.mp4
    - assets/strength/Split_squats.png
    - assets/strength/Split_squats.mp4
    - assets/reformer/Shoulder_shrug_video.mp4
    - assets/strength/Standing_fire_hydrants.png
    - assets/strength/Standing_fire_hydrants.mp4
    - assets/strength/Standing_lunge.png
    - assets/strength/Standing_lunge.mp4
    - assets/strength/Sumo_squats.png
    - assets/strength/Sumo_squats.mp4