// /*
// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyB_-jJtq7QEvPSqyZWlr7Dj0gbFLxFqX18',
//     appId: '1:399739685326:web:538a02bba496c79ccc439f',
//     messagingSenderId: '399739685326',
//     projectId: 'fitness-app-f6766',
//     authDomain: 'fitness-app-f6766.firebaseapp.com',
//     storageBucket: 'fitness-app-f6766.appspot.com',
//     measurementId: 'G-LEVX25H6V6',
//   );
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyCGFT9dZp9mG8Xxq9pGXU5j4qbtT2y5470',
//     appId: '1:399739685326:android:67677f4fe4c6e039cc439f',
//     messagingSenderId: '399739685326',
//     projectId: 'fitness-app-f6766',
//     storageBucket: 'fitness-app-f6766.appspot.com',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyD_HScc7l_s6zm9PHxMB5qwmwsnm0AkQIM',
//     appId: '1:399739685326:ios:5c4411dd60404403cc439f',
//     messagingSenderId: '399739685326',
//     projectId: 'fitness-app-f6766',
//     storageBucket: 'fitness-app-f6766.appspot.com',
//     iosBundleId: 'com.example.newfitnessapp',
//   );
// }
// */
